version: '3.8'
services:
  emailconsumer:
    build: .
    container_name: email-consumer
    environment:
      - Kafka__BootstrapServers=kafka:9092
    networks:
      - trainerapi_trainers-network

networks:
  trainerapi_trainers-network:
    external: true